baseURL = 'https://iamyanik.github.io/where-is-hugo/'
languageCode = 'en-us'
title = 'My New Hugo Project'
theme = "hugo-coder"
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
author = "Yanik"
description = "I'm just fucking around and finding out"
keywords = "blog,developer,personal"
info = ["Junior Network Engineer", "professional cutie"]
avatarURL = "images/avatar.jpg"
dateFormat = "01. January 2001"
since = 2019
